[project]
name = "alpolimibot"
version = "0.1.0"
description = "Trova le aule libere e guarda lo stato di occupazione della biblioteca direttamente da Telegram"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.30.0",
    "beautifulsoup4>=4.14.3",
    "psycopg2-binary>=2.9.11",
    "python-dotenv>=1.0",
    "requests>=2.32.5",
]
