{
 "title": "@alpolimibot - Utenti e Reports",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Comandi più usati OGGI",
   "type": "table",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "polimi_aule_prod",
     "rawSql": "\nSELECT \n    action,\n    COUNT(*)\nFROM activity_log\nWHERE date(ts) = CURRENT_DATE\nGROUP BY action\nORDER BY count DESC;"
    }
   ]
  },
  {
   "title": "Comandi più usati",
   "type": "table",
   "gridPos": { "h": 12, "w": 7, "x": 5, "y": 0 },
   "targets": [
    {
     "dataset": "polimi_aule_prod",
     "rawSql": "SELECT action, count(*) FROM activity_log \nGROUP BY action\nORDER BY count DESC"
    }
   ]
  },
  {
   "title": "Utenti",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "polimi",
     "rawSql": "SELECT count(*) FROM user_preference "
    }
   ]
  },
  {
   "title": "Nuovi utenti",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "polimi_aule_prod",
     "rawSql": "SELECT TO_CHAR(aggiornato_il, 'DD/MM/YYYY') as submission_date, count(*)\nFROM user_preference\nGROUP BY date(aggiornato_il), submission_date\nORDER BY date(aggiornato_il);"
    }
   ]
  },
  {
   "title": "Reports anonimi",
   "type": "table",
   "gridPos": { "h": 17, "w": 15, "x": 0, "y": 22 },
   "targets": [
    {
     "dataset": "polimi_aule_prod",
     "rawSql": "SELECT \n    TO_CHAR(inviato_il, 'DD/MM/YYYY HH24:MI') AS inviato_il, \n    messaggio \nFROM report \nORDER BY report.inviato_il DESC;"
    }
   ]
  },
  {
   "title": "Utenti",
   "type": "table",
   "gridPos": { "h": 17, "w": 9, "x": 15, "y": 22 },
   "targets": [
    {
     "dataset": "polimi_aule_prod",
     "rawSql": "SELECT * FROM user_preference ;"
    }
   ]
  }
 ]
}