{
 "title": "@alpolimibot - Occupazione aula",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "aula",
    "label": "Aula",
    "query": {
     "query": "SELECT DISTINCT sigla AS __text, idaula::text AS __value \nFROM aula \nWHERE visible = TRUE \nORDER BY 1;"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Informazioni aula $aula",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "polimi_aule_prod",
     "rawSql": "SELECT \n    sigla as \"Sigla\",\n    capienza as \"Capienza\",\n    has_power_sockets AS \"Prese Elettriche\",\n    has_network_sockets AS \"Prese Rete\"\nFROM aula\nWHERE idaula = '$aula'::integer;"
    }
   ]
  },
  {
   "title": "Occupazione Aula $aula per il giorno $giorno",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "dataset": "polimi_aule_prod",
     "rawSql": "SELECT \n    ((g.data + s.inizio) AT TIME ZONE 'Europe/Rome') AS \"time\",\n    ((g.data + s.fine) AT TIME ZONE 'Europe/Rome') AS \"time_end\",\n    COALESCE(s.corso, 'Occupato') AS \"Stato / Corso\"\nFROM occupazione_giorno g\nJOIN occupazione_slot s ON g.id = s.id_giorno\nWHERE g.idaula = '$aula'::integer\n  AND $__timeFilter((g.data + s.inizio)::timestamp)\nORDER BY s.inizio ASC;"
    }
   ]
  },
  {
   "title": "Occupazione Aula $aula per il giorno $giorno.",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "dataset": "polimi_aule_prod",
     "rawSql": "SELECT \n    TO_CHAR(g.data, 'DD/MM/YYYY') AS \"Data\",\n    TO_CHAR(s.inizio, 'HH24:MI') AS \"Ora Inizio\",\n    TO_CHAR(s.fine, 'HH24:MI') AS \"Ora Fine\",\n    COALESCE(s.corso, 'Occupato') AS \"Corso / Occupazione\"\nFROM occupazione_giorno g\nJOIN occupazione_slot s ON g.id = s.id_giorno\nWHERE g.idaula = '$aula'::integer\n  AND $__timeFilter((g.data + s.inizio)::timestamp)\nORDER BY g.data DESC, s.inizio ASC;"
    }
   ]
  }
 ]
}