{
 "title": "@alpolimibot - Biblioteca",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Stato attuale",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "polimi_aule_prod",
     "rawSql": "SELECT DISTINCT ON (s.id)\n    s.name as \"Nome\",\n    o.occupancy_percent as \"Occupazione\",\n    o.is_open as \"Stato\",\n    o.fetched_at as \"Ultimo aggiornamento\"\nFROM affluences_sites s\nJOIN affluences_occupancies o ON s.id = o.site_id\nORDER BY s.id, o.fetched_at DESC;"
    }
   ]
  },
  {
   "title": "Numero record",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "polimi_aule_prod",
     "rawSql": "SELECT count(*)\nFROM public.affluences_occupancies"
    }
   ]
  },
  {
   "title": "Affluences Sites",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "dataset": "polimi_aule_prod",
     "rawSql": "SELECT\n  id,\n  slug,\n  affluences_id\nFROM public.affluences_sites\nORDER BY id ASC\n"
    }
   ]
  },
  {
   "title": "Numero giorni registrati",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "polimi_aule_prod",
     "rawSql": "SELECT count(distinct(date(fetched_at)))\nFROM public.affluences_occupancies"
    }
   ]
  },
  {
   "title": "Occupazione biblioteche",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "dataset": "polimi_aule_prod",
     "rawSql": "SELECT\n  o.fetched_at AS \"time\",\n  o.occupancy_percent AS \"Biblioteca Bovisa La Masa - Politecnico di Milano\"\nFROM affluences_occupancies o\nWHERE $__timeFilter(o.fetched_at) and o.site_id = 1"
    },
    {
     "dataset": "polimi_aule_prod",
     "rawSql": "SELECT\n  o.fetched_at AS \"time\",\n  o.occupancy_percent AS \"Biblioteca Bovisa Candiani - Politecnico di Milano\"\nFROM affluences_occupancies o\nWHERE $__timeFilter(o.fetched_at) and o.site_id = 2"
    },
    {
     "dataset": "polimi_aule_prod",
     "rawSql": "SELECT\n  o.fetched_at AS \"time\",\n  o.occupancy_percent AS \"Biblioteca Campus Leonardo - Politecnico di Milano\"\nFROM affluences_occupancies o\nWHERE $__timeFilter(o.fetched_at) and o.site_id = 3"
    }
   ]
  },
  {
   "title": "Stato apertura",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "dataset": "polimi_aule_prod",
     "rawSql": "SELECT\n  o.fetched_at AS \"time\",\n  o.is_open AS \"Biblioteca Bovisa La Masa - Politecnico di Milano\"\nFROM affluences_occupancies o\nWHERE $__timeFilter(o.fetched_at) and o.site_id = 1"
    },
    {
     "dataset": "polimi_aule_prod",
     "rawSql": "SELECT\n  o.fetched_at AS \"time\",\n  o.is_open AS \"Biblioteca Bovisa Candiani - Politecnico di Milano\"\nFROM affluences_occupancies o\nWHERE $__timeFilter(o.fetched_at) and o.site_id = 2"
    },
    {
     "dataset": "polimi_aule_prod",
     "rawSql": "SELECT\n  o.fetched_at AS \"time\",\n  o.is_open AS \"Biblioteca Campus Leonardo - Politecnico di Milano\"\nFROM affluences_occupancies o\nWHERE $__timeFilter(o.fetched_at) and o.site_id = 3"
    }
   ]
  }
 ]
}