{
 "title": "@alpolimibot - Aule",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Numero aule",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "flights", "rawSql": "SELECT count(*) FROM aula;" }
   ]
  },
  {
   "title": "Numero edifici",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "flights", "rawSql": "SELECT count(*) FROM edificio " }
   ]
  },
  {
   "title": "Aule dotate di prese elettriche",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "polimi",
     "rawSql": "SELECT COUNT(DISTINCT a.idaula) AS aule_con_prese\nFROM aula a\nJOIN aula_dotazione  ad ON ad.idaula           = a.idaula\nJOIN tipo_dotazione  td ON td.id               = ad.id_tipo_dotazione\nWHERE td.id = 142;"
    }
   ]
  },
  {
   "title": "Aule dotate di prese di rete",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "polimi",
     "rawSql": "SELECT COUNT(DISTINCT a.idaula) AS aule_con_prese\nFROM aula a\nJOIN aula_dotazione  ad ON ad.idaula           = a.idaula\nJOIN tipo_dotazione  td ON td.id               = ad.id_tipo_dotazione\nWHERE td.id = 143;"
    }
   ]
  },
  {
   "title": "Giorni registrati",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "flights",
     "rawSql": "SELECT count(distinct(data)) from occupazione_giorno "
    }
   ]
  },
  {
   "title": "Ultimo giorno registrato",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "flights",
     "rawSql": "SELECT  to_char(data, 'DD/MM/YY') as ultima_data from occupazione_giorno \norder by data desc\nlimit 1;"
    }
   ]
  },
  {
   "title": "Ultimo aggiornamento",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "flights",
     "rawSql": "SELECT to_char(scaricato_il, 'DD/MM/YY') from occupazione_giorno \norder by scaricato_il desc\nlimit 1"
    }
   ]
  },
  {
   "title": "Aggiornamenti dati aule",
   "type": "table",
   "gridPos": { "h": 24, "w": 10, "x": 0, "y": 4 },
   "targets": [
    {
     "dataset": "flights",
     "rawSql": "SELECT\n    a.idaula                                            AS \"ID\",\n    a.sigla                                             AS \"Sigla\",\n    TO_CHAR(MIN(og.data), 'DD/MM/YYYY')                 AS \"Primo giorno in archivio\",\n    TO_CHAR(MAX(og.data), 'DD/MM/YYYY')                 AS \"Ultimo giorno in archivio\",\n    TO_CHAR(MAX(og.scaricato_il), 'DD/MM/YYYY')         AS \"Data ultimo aggiornamento\",\n    COUNT(DISTINCT og.data)                             AS \"Numero giorni in archivio\" \n    \nFROM aula a\nLEFT JOIN occupazione_giorno og ON og.idaula = a.idaula\nLEFT JOIN edificio e  ON e.csie  = a.csie\nLEFT JOIN campus   ca ON ca.csic = e.csic\nGROUP BY a.idaula, a.sigla, ca.nome\nORDER BY sigla"
    }
   ]
  },
  {
   "title": "Aule dotate di prese di rete",
   "type": "table",
   "gridPos": { "h": 18, "w": 5, "x": 10, "y": 4 },
   "targets": [
    {
     "dataset": "polimi",
     "rawSql": "SELECT\n    a.idaula AS \"ID\",\n    a.sigla AS \"Sigla\",\n    a.capienza AS \"Capienza\",\n    s.nome  AS \"Sede\"\nFROM aula a\nJOIN aula_dotazione  ad ON ad.idaula           = a.idaula\nJOIN tipo_dotazione  td ON td.id               = ad.id_tipo_dotazione\nLEFT JOIN edificio e  ON e.csie  = a.csie\nLEFT JOIN campus   ca ON ca.csic = e.csic\nLEFT JOIN sede     s  ON s.csis  = ca.csis\nWHERE td.id = 143\nORDER BY a.sigla;"
    }
   ]
  },
  {
   "title": "Aule dotate di prese di corrente",
   "type": "table",
   "gridPos": { "h": 18, "w": 5, "x": 15, "y": 4 },
   "targets": [
    {
     "dataset": "polimi",
     "rawSql": "SELECT\n    a.idaula AS \"ID\",\n    a.sigla AS \"Sigla\",\n    a.capienza AS \"Capienza\",\n    s.nome  AS \"Sede\"\nFROM aula a\nJOIN aula_dotazione  ad ON ad.idaula           = a.idaula\nJOIN tipo_dotazione  td ON td.id               = ad.id_tipo_dotazione\nLEFT JOIN edificio e  ON e.csie  = a.csie\nLEFT JOIN campus   ca ON ca.csic = e.csic\nLEFT JOIN sede     s  ON s.csis  = ca.csis\nWHERE td.id = 142\nORDER BY a.sigla;"
    }
   ]
  }
 ]
}